---

- name: Gluster Create Volume | Peer all servers
  shell: "gluster peer probe {{ item }}"
  with_items: all_nodes
  when: ansible_default_ipv4.address != item

- name: Gluster Create Volume | Building string p.1
  shell: "echo {{item}}:{{ gluster_dir }}/{{ volume_name }}"
  with_items: nodes
  register: out_tmp

- name: Gluster Create Volume | Building string p.2
  set_fact: final_string="{{ out_tmp.results | map(attribute='stdout') | join(' ')}}"

- debug: var=final_string

- name: Gluster Create Volume | Create volume
  shell: "gluster volume create {{ volume_name }} {{ final_string }} force"

- name: Gluster Create Volume | Start volume
  shell: "gluster volume start {{ volume_name }}"

#- name: Gluster Create Volume | Mount gluster
#  mount: name=/mnt
#         src="{{ ansible_default_ipv4.address }}/{{ volume_name }}"
#         fstype=glusterfs
#         state=mounted
#
#- name: Gluster Create Volume | Create directories in cluster p.1
#  file: path=/mnt/shared state=directory mode=0755
#
#- name: Gluster Create Volume | Create directories in cluster p.2
#  file: path=/mnt/internals state=directory mode=0755
#
#- name: Gluster Create Volume | Unmount gluster
#  mount: name=/mnt
#         state=unmounted