---

- name: Gluster Create Volume | Peer all servers
  shell: "gluster peer probe {{ item }}"
  with_items: all_nodes
  when: ansible_default_ipv4.address != item

- name: Gluster Create Volume | Building string p.1
  shell: "echo {{item}}:/data/brick1/{{ volume_name }}"
  with_items: nodes
  register: out_tmp

- name: Gluster Create Volume | Building string p.2
  set_fact: final_string="{{ out_tmp.results | map(attribute='stdout') | join(' ')}}"

- debug: var=final_string

- name: Gluster Create Volume | Create volume
  shell: "gluster volume create {{ volume_name }} {{ final_string }} force"

- name: Gluster Create Volume | Start volume
  shell: "gluster volume start {{ volume_name }}"