---

- hosts: hot_tier

  roles:
    - role: gluster_configure
      volume_name: gv0
      sudo: yes

- hosts: bastion

  roles:
    - role: gluster_attach_volume
      nodes: "{{ groups.hot_tier }}"
      volume_name: gv0
      sudo: yes