---

- hosts: cold_tier

  roles:
    - role: gluster_configure
      volume_name: "{{ VOLUME_NAME }}"
      sudo: yes

- hosts: bastion

  roles:
    - role: gluster_create_volume
      nodes: "{{ groups.cold_tier }}"
      all_nodes: "{{ groups.cluster }}"
      volume_name: "{{ VOLUME_NAME }}"
      sudo: yes