---

- hosts: hot_tier

  roles:
    - role: gluster_configure
      volume_name: "{{ VOLUME_NAME }}"
      sudo: yes

- hosts: bastion

  roles:
    - role: gluster_attach_tier
      nodes: "{{ groups.hot_tier }}"
      volume_name: "{{ VOLUME_NAME }}"
      sudo: yes