# Cold tier is the nodes that will host cold tier glusterfs
# layer. This hosts should be internal IPs.
[cold_tier]
192.168.100.240
192.168.100.241

# Hot tier is the nodes that will host hot tier glusterfs
# layer. This hosts should be internal IPs.
[hot_tier]
192.168.100.242
192.168.100.243

[cluster:children]
hot_tier
cold_tier

# The entry point to the cluster. This IP is public.
[bastion]
83.149.198.48

[local]
127.0.0.1