# Cold tier is the nodes that will host cold tier glusterfs
# layer. This hosts should be internal IPs.
[cold_tier]
192.168.100.231
192.168.100.230

# The entry point to the cluster. Has public IP.
[bastion]
83.149.198.48

[local]
127.0.0.1